### ISSUE TITLE
Make image smaller by stripping symbols and maybe compressing

### ISSUE THREAD

**Issue by afbjorklund** [containers/PodmanHello#13]
Currently the binary still contains debuginfo, making it bigger:

glibc (ubi9)
```
1.7M	hello/usr/local/bin/podman_hello_world
728K	hello/usr/local/bin/podman_hello_world
```

musl (alpine)
```
76K	hello/usr/local/bin/podman_hello_world
16K	hello/usr/local/bin/podman_hello_world
```

After adding a `strip` command, it reduces in size by 2x or 4x.

----

~~That can be made even smaller, by compressing it with `upx`.~~

* #12

EDIT: Never mind, that broke the binary. Or made it slightly bigger.

```
localhost/hello                strip          63a7f1bbeb09  3 minutes ago   19.3 kB
localhost/hello                brute          62e8064e3709  3 hours ago     35.2 kB
localhost/hello                alpine         aae615db4fb7  3 hours ago     82.3 kB
localhost/hello                redhat         36c9b6960a0d  3 hours ago     1.7 MB
```

**Comment by afbjorklund** [comment]
It was the --brute or --ultra-brute options to `upx`, that were too aggressive...

Final size, after strip+upx, is 13k on amd64 and 15k on arm64. 100x smaller.

```
localhost/hello-arm64          latest         e5b636975da6  9 seconds ago   15.7 kB
localhost/hello-amd64          latest         cad888a69382  2 minutes ago   13.7 kB
```

EDIT: Then again, probably not worth it since it makes it less portable as well..

```console
$ podman run --platform=linux/arm64 localhost/hello-arm64
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

So better to avoid the compression, and settle for removing the debuginfo?

**Comment by rhatdan** [comment]
Opening a PR?

**Comment by afbjorklund** [comment]
Sure, here it is. (#14)

Corrected the title, it was not the debuginfo (only generated with `-g` compiler flag), but it was about _all_ symbols...

I will leave reverting the image from glibc back to musl up to you, I gather it was more of an UBI agenda behind it?

* #11
