### ISSUE TITLE
image is only linux/amd64

### ISSUE THREAD

**Issue by benoitf** [containers/PodmanHello#6]
image should be multi-arch, it's only for `linux/amd64` https://quay.io/repository/podman/hello?tab=tags&tag=latest

For example I can't run it on macOS

```
podman run hello                                                                                                                  
Resolved "hello" as an alias (/etc/containers/registries.conf.d/000-shortnames.conf)
Trying to pull quay.io/podman/hello:latest...
Getting image source signatures
Copying blob sha256:49c2a4621bd4c63023db9996911cf80833e9e251e015dc9b6f630025a7a7eb3e
Copying config sha256:633eb872fc662b2f070514927075745206904c96442aace19754cdab171dc4c7
Writing manifest to image destination
WARNING: image platform (linux/amd64) does not match the expected platform (linux/arm64)
qemu-x86_64-static: /usr/local/bin/podman_hello_world: Unable to find a guest_base to satisfy all guest address mapping requirements
  0000000000000000-0000000000000fff
  0000000000400000-00000000004047ef
```

image has been updated 2 days ago and it was working fine before

**Comment by cfergeau** [comment]
This is not what the issue is about, but in addition to the missing arm64 image, there is this known issue when trying to run the amd64 image on arm64: `Unable to find a guest_base to satisfy all guest address mapping requirements` - it's tracked in https://bugzilla.redhat.com/show_bug.cgi?id=2256916

**Comment by rhatdan** [comment]
Since the PR was merged, can this issue be closed?

**Comment by benoitf** [comment]
I think we're missing the credentials in the settings so action will succeed 

https://github.com/containers/PodmanHello/actions (current action failed to publish as credentials are not yet configured)

**Comment by benoitf** [comment]
fixed now
